<?php

@define('_loi1404','Page not found');
@define('_loi2404','Sorry but the page you are looking for does not exist, has been removed.
name changed or temporarily unavailable');
@define('_loi3404','Back to homepage');
@define('_goidien','Call');
@define('_goidien','Call');
@define('_chiduong','Directions');
@define('_thongbao','Notice');
@define('_hethogloi','System error');
@define ('_clickdoi','Click here if you dont want to wait');
@define ('_guibinhluanthanhcong','Comment submission successful');
@define('_noidungdangcapnhat','Content updating');
@define('_chuanhaptukhoa','No keyword entered');
@define ('_nhaptukhoatimkiem','Enter search keyword');
@define ('_xinnhaphoten','Please enter your full name');
@define ('_xinnhapdiachi','Please enter address');
@define ('_xinnhapemail','Please enter email');
@define('_nhapdiachiemail','Please enter email');
@define('_checkemail','Invalid email');
@define ('_xinnhapdienthoai','Please enter phone number');
@define ('_checkdienthoai','Invalid phone number');
@define('_xinnhapnoidung','Please enter text');
@define('_xinnhaptieude','Please enter title');
@define('_chude','Theme');
@define('_dangkythanhcong','Registration successful');
@define('_dangkykhongthanhcong','Registration failed');
@define ('_count_dangky','You have reached the limit of registrations. Please come back later');
@define('_emaildaduocdangky','Email already registered');
@define('_loicaptcha','Invalid captcha please try again later.');

@define('_diachi','Address');
@define('_ngongu','Language');
@define('_hotline','Hotline');
@define('_trangchu','Home');
@define('_gioithieu','About');
@define('_dichvu','Service');
@define('_doitac','Partner');
@define('_tuyendung','Recruitment');
@define('_daotao','Training');
define('_sanpham','Product');
@define('_tintuc','News');
@define('_lienhe','Contact');
@define('_timkiem','Search');
@define('_khongtimthay','not found');
@define('_chungchiiso','Iso certificate');
@define('_cungcapdichvu','Provide service');
@define('_tatca','All');
@define('_now','date');
@define('_hang','month');
@define('_nam','year');
@define('_xemtatca','View All');
@define('_xemthem','See also');
@define('_cameravideo','Camera - Videos');
@define('_danhgiakhachhang','Customer Review');
@define ('_dangkynhantin','Subscribe');
@define('_hoten','Full name');
@define('_email','Email');
@define('_dienthoai','Phone');
@define('_noidung','Content');
@define ('_guithongtinlienhe','Send contact info');
@define ('_online','Online');
@define('_accesscapthang','Access month');
@define('_tongtruycap','Total counter');

@define('_trangchu','Home');
@define('_gioilamviec','Business hours');
@define('_giohang','Cart');
@define('_sanpham','Product');
@define('_camnang','Manual');
@define('_bosuutap','Collection');
@define('_nhaptukhoa','Enter keyword');
@define('_chonvideo','Select video');
@define('_docthem','Read more');
@define ('_gianhapcung','Join with');
@define ('_dangkynhanthongtin','Subscribe to receive information');
@define('_cuahang','Store');
@define('_thongtinvesala','Sala info');
@define ('_giaychungnhan','Business registration certificate');
@define('_thietke','Design');
@define('_gia','Price');
@define('_dathang','Order');
@define('_themvaogiohang','Add to cart');
@define('_muangay','Buy now');
@define('_themsanpham','Add Product');
@define ('_vaogiohangthanhcong','Add to cart');
@define('_bancochacchanxoasp','Are you sure to delete the product');
@define ('_xinchonthanhpho','Please select a city');
@define ('_xinchonquanhuyen','Please select a district');
@define ('_bancomuonxoatoanbogiohang','Do you want to delete the entire cart');
@define('_sanphamlienquan','Related Products');
@define('_pname','Product Name');
@define('_price','Price');
@define('_quantity','Quantity');
@define('_total_price','Total price');
@define('_congcu','Tools');
@define('_xacnhanthanhtoan','Payment Confirmation');
@define('_thanhtoan','Payment');
@define('_thongtinnhanhang','Receiving information');
@define('_hinhthucthanhtoan','Form of payment');
@define('_thongtindonhang','Order info');


@define('_chitietsanpham','Product Details');
@define('_clickvao','Click here if you dont want to wait too long');
@define('_thongbao','Notice');
@define('_camon','Thanks');
@define ('_chuamuasanpham','Havent purchased the product');
@define('_donhangchuacosanpham','Order has no products');
@define ('_xinloiquykhach','Sorry sir');
@define('_ghichu','Note');
@define ('_quanhuyen','District');
@define('_tinhthanhpho','City');
@define('_thongtinthanhtoan','Payment info');
@define('_xoatatca','Delete all');
@define('_muatiep','Buy more');
@define('_tonggia','Total Price');
@define('_congcu','Tools');
@define('_soluong','Amount');
@define('_gia','Price');
@define('_tensanpham','Product Name');
@define ('_sanphamxemnhieu','Most viewed products');
@define('_baivietmoinhat','Latest Post');
@define('_listmuc','Category');
@define('_danhmucsanpham','Product Category');
@define('_dangboi','Posted by');
@define('_vaoluc','at');
@define('_voitukhoa','with keyword');
@define('_lienquan','Related');
@define('_masanpham','Product ID');
@define('_giohanghienco','Existing cart');
@define('_sanphamvuaduocthem','Product just added');
@define('_vaogiohang','Add to cart');
@define ('_tienhanhthanhtoan','Proceed to payment');

@define('_ngaydang','Post date');
@define('_tinlienquan','Related news');
@define('_luotview','View');
@define('_thongtinchitiet','Details');
@define('_binhluanfacebook','facebook comment');
@define('_goidien','Call');
@define('_nhantin','Messaging');
@define('_emailcuaban','Your email');
@define('_dangky','Register');
@define('_ngaydang','Post date');
@define('_mota','Description');
@define('_thongtinchitiet','Details');
@define('_binhluanfacebook','facebook comment');
@define('_baivietkhac','Other Post');
@define('_chitietsanpham','Product Details');
@define('_sanphamlienquan','Related Products');
@define('_thongtinlienhe','Contact info');
@define ('_lienhechungtoi','Contact us');
@define('_danghangthanhcong','Order successful');


@define('_sanphammoi','New Product');
@define('_xemthem','See More');
@define('_trusochinh','Headquarters');
@define('_dangkybaogia','Register for Quotation');
@define ('_chinhsachvahotro','Policy & Support');
@define('_nhamaysanxuat','Factory');
@define('_ketnoi','Connection');
@define('_new1','New');
@define('_duannoibat','Featured Project');
@define('_price','Make an appointment');
@define ('_dienn','Fill out the form below to receive our latest offers');
@define('_dangkyngay','Register now');
@define('_tuvan','advise');
@define('_noibat','featured');
@define('_giaiphap','Solution');
@define('_xuatnhapkhau','Import/Export');
@define('_duan','Project');
@define('_ma','SP Code');
@define('_duancuachungtoi','Our project');
@define('_giaiphapnoibat','Featured Solution');


@define ('_baiviet','News');
@define ('_luotxem','View');
@define ('_ctys','IMPORT AND MANUFACTURING COMPANY LIMITED');


?>